### ISSUE TITLE
"wrong type for with_prefix" for flattening BTreeMap

### ISSUE THREAD

**Issue by deklanw** [jonasbb/serde_with#115]
```rust
use std::collections::BTreeMap;

use serde::Serialize;
use serde_with::with_prefix;

#[derive(Hash, PartialEq, Eq, Debug, Serialize, Ord, PartialOrd)]
enum Foo {
    One, Two, Three
}

#[derive(Hash, PartialEq, Eq, Debug, Serialize, Ord, PartialOrd)]
struct Data {
    stuff: String,

    #[serde(flatten, with = "foo")]
    foo: BTreeMap<Foo, i32>,
}
with_prefix!(foo "foo_");

fn main() {
    let mut my_foo = BTreeMap::new();
    my_foo.insert(Foo::One, 1);
    my_foo.insert(Foo::Two, 2);
    my_foo.insert(Foo::Three, 3);

    let row = Data {
        stuff: "Stuff".to_owned(),
        foo: my_foo
    };

    let my_str = serde_json::to_string(&row).unwrap();
    println!("{}", my_str);
}
```

I'm expecting to see

`{"stuff":"Stuff","foo_One":1,"foo_Two":2,"foo_Three":3}`

but I get `Error("wrong type for with_prefix", line: 0, column: 0)',`

If I just use the regular serde flatten I get

`{"stuff":"Stuff","One":1,"Two":2,"Three":3}`

**Comment by jonasbb** [comment]
Thanks for the report. I think this can be fixed if the serialization is forced to be a string. The serde enum variant serialization code requires `'static str`, which cannot be created.

But if I force them to be serialized as strings, then the prefix can be applies. Now this will change the serialization format for some formats, but the `with_prefix` will probably only be used together with serialization formats which serialize it as a string anyway. I created #116 with the necessary code.
