### ISSUE TITLE
links to the user guide don't work

### ISSUE THREAD

**Issue by davepacheco** [jonasbb/serde_with#137]
The [documentation for the latest release](https://docs.rs/crate/serde_with/1.5.0-alpha.1) has a few links to the user guide (in the first section, and also where it links to "feature flags").  These don't seem to work from any where I've tried to click them.  They don't work from [the docs.rs page for the crate](https://docs.rs/crate/serde_with/1.5.0-alpha.1), the [docs.rs docs page for the same release](https://docs.rs/serde_with/1.5.0-alpha.1/serde_with/), or the [rendered GitHub README](https://github.com/jonasbb/serde_with/blob/master/README.md).  I'm not sure where to find the guide.

**Comment by jonasbb** [comment]
https://docs.rs/serde_with/1.5.0-alpha.1/serde_with/guide/index.html

Thanks for the report. I see if I can improve the situation temporarily.
The docs.rs links link to the latest stable version, but the 1.5.0 is still in the alpha phase. The links should get fixed when 1.5.0 is released.

**Comment by davepacheco** [comment]
Thanks!  That's very helpful.
