### ISSUE TITLE
`string_empty_as_none` can not handle miss field

### ISSUE THREAD

**Issue by s97712** [jonasbb/serde_with#160]
Without `string_empty_as_none`, if miss `Option<T>` field, I get `None`, with `string_empty_as_none` I only get the miss field error.

**Comment by jonasbb** [comment]
This affects any code using `with` or `deserialize_with` and cannot be avoided.
However, you can add `default` to the serde attribute. This can deserialize a missing field and turns it into `None`.

```rust
    #[serde(default, with = "string_empty_as_none")]
    field: Option<String>,
```

**Comment by jonasbb** [comment]
@s97712 Does adding `default` to the attribute solve your problem?

**Comment by s97712** [comment]
Thanks. That solves my problem.
