### ISSUE TITLE
Feature request: `serde_as` attribute: allow usage with re-exported `serde_with` crate at different path 

### ISSUE THREAD

**Issue by tobz1000** [jonasbb/serde_with#207]
It would be useful for my scenario to allow the `serde_as` attribute macro to function with the `serde_with` crate rooted at an alternate path - equivalently to Serde's [`#[serde(crate = "...")]`](https://serde.rs/container-attrs.html#crate) attribute.

As the Serde docs mention, this would be used when a deserialise impl is being generated from within another macro. By re-exporting `serde_with` from my own crate, I allow consumers to not have to add the crate to their own manifest - and removing/modifying my usage of `serde_with` in future does not become a breaking change.

Happy to work on this if you'd like.

**Comment by jonasbb** [comment]
Hi @tobz1000, that sounds like a nice addition. I have not paid special considerations for this problem, so there might be a couple of places which either assume that `serde_with` or `serde` is available.

`serde` is already re-exported from `serde_with`, so this should be used to replace all references of `serde`.
https://github.com/jonasbb/serde_with/blob/eb1c52dbea9f0a7d4c2e5f9b8a9f74f8af77c01d/src/lib.rs#L203-L204

I think all the macros need to be checked if they assume any crate name. `with_prefix!` is hopefully correctly implemented.

I would appreciate the help if you want to start working on this already. Feel free to submit individual PRs for the parts you need. That way it is a less overwhelming task.

**Comment by tobz1000** [comment]
Thanks for merging :) I will have a look at updating the guide documentation, and making necessary changes to other macros, when I can.

**Comment by tobz1000** [comment]
I see you're working on other parts of this issue (#217) - is there anything else you would like me to tackle that you're not already doing?

**Comment by jonasbb** [comment]
I think the only thing missing now is writing the documentation for #217. I get to that at least over the weekend. After that I can release a new version.
