### ISSUE TITLE
Use clippy's MSRV support when available

### ISSUE THREAD

**Issue by jonasbb** [jonasbb/serde_with#227]
Nightly clippy supports specifying the MSRV which disables lints incompatible with this Rust versions, e.g., because it requires library functions not yet available.
https://github.com/rust-lang/rust-clippy/blob/master/README.md#specifying-the-minimum-supported-rust-version
This is not yet available on stable clippy, so it cannot be used yet, since then clippy complains about unknown keys in the config file.
The alternative, custom inner attributes, is not yet stable in Rust and also cannot be used.

At some point, clippy will hopefully support the `rust-version` field from `Cargo.toml` (https://github.com/rust-lang/rust-clippy/issues/7765) such that it is not necessary to have a separate configuration just for clippy.

**Comment by hellow554** [comment]
https://github.com/rust-lang/rust-clippy/pull/8774 has been merged and will be available on nightly once clippy has been updated in the main repo. Just for your information ;)

Don't know when it hits stable, probably 1.64.

**Comment by jonasbb** [comment]
Thanks for the information and for actually implementing the feature :) That hopefully means that future clippy versions will make fewer bad suggestions. The MSRV on the master branch is currently quite high, so this will likely not affect many places.
