### ISSUE TITLE
#[serde_as(as = X)] fails silently without the quotes

### ISSUE THREAD

**Issue by Lehona** [jonasbb/serde_with#233]
When forgetting to add quotes to the type-string within the serde_as macro, the macro seems to do nothing, but won't throw an error, either. This results in the compiler complaining about the field in question not implementing De/Serialize. Example:

Works:
```
#[serde_as]
#[pyclass]
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct Container {
    #[pyo3(get, set)]
    #[serde_as(as = "Vec<LocalPy<Inner>>")]
    pub inner: Vec<Py<Inner>>,
}
```

Fails because `Py<Inner>` does not implement De/Serialize:
```
#[serde_as]
#[pyclass]
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct Container {
    #[pyo3(get, set)]
    #[serde_as(as = Vec<LocalPy<Inner>>)]
    pub inner: Vec<Py<Inner>>,
}
```

I guess you're using some kind of if-let on the structure of the macro and ignoring any incorrectly-constructed macros rather than throwing a compile-error if the macro structure does not match your expectations.

I hope you don't mind the frequent issues.

**Comment by jonasbb** [comment]
That is an issue indeed. I assumed the parsing crate (darling) would handle this. I have not found a way to get an error in this case.
I think this is the same issue as described in https://github.com/TedDriggs/darling/issues/96.

> I hope you don't mind the frequent issues.

Please, keep them going. I like seeing people use this crate and getting issues or comments is the only way to know with what people struggle.

**Comment by jonasbb** [comment]
This will be fixed by upgrading darling after https://github.com/TedDriggs/darling/pull/113 gets merged.

Another issue I should probably warn about is adding an empty `serde_as` attribute on a field like
```rust
    // Warn or error on these
    #[serde_as()]
    no_modifiers: u32,
    #[serde_as]
    empty: u32,
```

These are not really wrong, just confusing as they will perform no change.

This only applies to fields and not to the proc-macro before structs, i.e,

```rust
#[serde_as]
#[derive(Serialize)]
struct S()
```
