### ISSUE TITLE
Provide a deserialize_ignore_any function

### ISSUE THREAD

**Issue by lovasoa** [jonasbb/serde_with#250]
Hello !
  Would you be interested in providing the following function : 

```rust
fn deserialize_ignore_any<'de, D: Deserializer<'de>, T:Default>(deserializer: D) -> Result<T, D::Error> {
    serde::de::IgnoredAny::deserialize(deserializer).map(|_| T::default())
}
```

It is useful in combination with `#[serde(deserialize_with = "...")` when a field should accept any value without actually storing  its contents. 

In particular, it can be used to work around the fact that `#[serde(other)]` doesn't work with non-unit enum variants, with for instance : 

```rust
#[derive(Deserialize)]
enum Item {
    Foo, Bar, Baz,
    #[serde(other, deserialize_with = "deserialize_ignore_any")]
    Other,
}
```

**Comment by jonasbb** [comment]
Hi, thanks for the interest in this project. The function fits the scope of this project and could be added.

However, it seems your example does not what you intend it to do:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bec97a5a7ea17fc21ba46af3e80d1453

Do you have another use-case for this function or an alternative implementation?

**Comment by lovasoa** [comment]
The function does work as expected. I'm not sure I understand what you are trying to do in the playground example. If you are trying to deserialize a list of strings, you don't need deserialize_ignore_any at all. It is helpful in cases like this, for example: https://github.com/RReverser/serde-xml-rs/issues/55#issuecomment-768902802

**Comment by jonasbb** [comment]
`#[serde(other)]` declares an enum variant as fallback. `"Ba"` does not deserialize to any enum variant so in the playground it falls back to `Other`. However, if I add the `deserialize_with` attribute I get this error while deserializing: `Err(Error("invalid type: unit variant, expected newtype variant", line: 0, column: 0))`. The code deserializes the correct enum variant if you change `"Ba"` to `"Foo"`, `"Bar"`, or `"Baz"`.

I will check the serde-xml link later.

**Comment by lovasoa** [comment]
Ok, I understand what you were trying to do. Indeed, deserialize_ignore_any does not work in that case, because `deserialize_with` hints the serde that you are trying to deserialize the contents of the enum variant, and the string **is** the enum variant, but does not have any contents. If you want an example where using  deserialize_ignore_any may be useful in conjunction with `other` in serde_json, see for instance: 

```rust
use serde::*;

fn main() {
    println!("{:?}", serde_json::from_str::<Vec<Item>>(r#"[{"y":1}, {"x":1}]"#));
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum Item {
    Foo{x: u8},
    #[serde(deserialize_with = "deserialize_ignore_any")]
    Other,
}

fn deserialize_ignore_any<'de, D: Deserializer<'de>>(
    deserializer: D,
) -> Result<(), D::Error> {
    serde::de::IgnoredAny::deserialize(deserializer).map(|_| ())
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=42586d7bee747df4b5b80684c64b3e0e)

**Comment by jonasbb** [comment]
Ok I think I understand now how this can be used.

1. It enabled the other variant in an enum (tagged with `#[serde(other)]` to consume data without failing the deserialization. This "breaks" deserialization of data-less enums (the `"Ba"` example above).
2. You can create an other-like enum variant in an `untagged` enum, which does not allow the `#[serde(other)]` attribute. It behaves similar to `Other(serde::de::IgnoredAny)`, but without the downside of including the `IgnoredAny` type.

@lovasoa  Do you want to create a pull request to add the method? It probably fits best in `src/rust.rs`. 

Is it possible to extend the method to support enums with and without data? Basically supporting this without any errors during deserialization.

```rust
use serde::*;

fn main() {
    println!("{:?}", serde_json::from_str::<Vec<Item>>(r#"[{"NotFoo": {"y":1}}, {"Foo": {"x":1}}, "NotBar", "Bar"]"#));
}

#[derive(Debug, Deserialize)]
enum Item {
    Bar,
    Foo{x: u8},
    #[serde(other)]
    #[serde(deserialize_with = "deserialize_ignore_any")]
    Other,
}

fn deserialize_ignore_any<'de, D: Deserializer<'de>, T:Default>(deserializer: D) -> Result<T, D::Error> {
    serde::de::IgnoredAny::deserialize(deserializer).map(|_| T::default())
}
```

**Comment by lovasoa** [comment]
> Is it possible to extend the method to support enums with and without data?

I don't think so, no. Serde will not even call the method when deserializing a string value for the enum. It will see that the code is expecting contents inside the enum variant, and that the data doesn't have it.  What you can do in this case is : 

```rust
#[derive(Debug, Deserialize)]
enum Item {
    Bar,
    Foo{x: u8},
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum ItemContainer {
    Item(Item),
    #[serde(deserialize_with = "deserialize_ignore_any")]
    Other,
}
```

I do admit that the usefulness is more limited with serde_json than with, for instance, serde-xml-rs, where  `#[serde(other, deserialize_with = "deserialize_ignore_any")]` is the only way of parsing a heterogeneous collection.
