### ISSUE TITLE
#[serde_as(as = "Option<OneOrMany<_>>")]#[skip_serializing_none] fails to deserialize with None

### ISSUE THREAD

**Issue by apps4uco** [jonasbb/serde_with#311]
I have this code which fails. I believe it should be supported.

~~~
#[serde_as]
#[skip_serializing_none]
#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct Demo {
    #[serde_as(as = "Option<OneOrMany<_>>")]
    contents: Option<Vec<String>>,
}
~~~

It serializes fine with a single element in a vector or multiple elements in a vector

It fails with an error when the contents are set to None

failures:

---- tests::vec_none stdout ----
None
Serialized ---
{}

Error: Message("missing field `contents`", Some(Pos { marker: Marker { index: 4, line: 2, col: 0 }, path: "." }))

Please find a test case attached.

Workaround: Dont specify #[skip_serializing_none] 

[test.txt](https://github.com/jonasbb/serde_with/files/6412010/test.txt)

**Comment by jonasbb** [comment]
You need to add `#[serde(default)]` as an attribute to the `contents` field too. It is the normal behavior for serde to disable the special treatment regarding missing fields whenever a `with` annotation is added. The `serde_as` is equivalent to the `with` in this regard.

There is an issue to maybe change that in the future #185.

```rust
    #[serde_as(as = "Option<OneOrMany<_>>")]
    #[serde(default)]
    contents: Option<Vec<String>>,
```

I hope that helps.

**Comment by apps4uco** [comment]
Great that fixes it. Maybe it could be added as an example to the documentation.

Thanks ever so much
