### ISSUE TITLE
Better support for `StringWithSeparator` with non-string types

### ISSUE THREAD

**Issue by filips123** [jonasbb/serde_with#318]
Currently `StringWithSeparator` only supports using `Display` and `FromStr` which is not as convenient when using non-string types (such as enums), because unlike Serde's normal `Serialize` and `Deserialize` traits, they cannot be derived automatically. This means developers need to write their own implementations, which can complicate things and also don't support some "fancy" Serde features like attributes for renaming or skipping, for example, enum variants (yes, this can still be done in the actual traits implementation, but doesn't look as good as declarative approch with attributes).

Is it possible to implement custom derive macro(s) that can automatically implement all traits needed by `StringWithSeparator` for simple non-string types (such as enums) with support for configuring them through attributes (preferably with standard Serde attributes)? I know not all types normally supported by Serde can be supported (for example, nested types), but for things like enums and types that hold strings, numbers, etc., I think it would be quite useful.

**Comment by jonasbb** [comment]
Could you share an example of what you are trying to achieve, ideally with the Rust structs and the serialized form? That would be helpful to have for discussion.

The implementation of `StringWithSeparator` is fixed to using `Display` and `FromStr`. However, the implementation is not particularly complex. So if you need other trait bounds, you can also copy the implementation and use other functions. Everything which converts to/from string should work.
<https://users.rust-lang.org/t/de-serialize-delimited-string-to-from-vec/54272>

> Is it possible to implement custom derive macro(s) that can automatically implement all traits needed by StringWithSeparator for simple non-string types (such as enums) [...]

There are crates, which allow you to derive `Display` and `FromStr`, for example `parse-display`.
If you need the full power of serde attributes, you should really use a `Serializer` which behaves as you want. `serde_plain` is one, which works quite well for simple enums.
Deriving `Display` or `FromStr` is out of scope for this crate.

**Comment by filips123** [comment]
Basically I wanted to serialize and deserialize list of enum variants into space-separated string. I used `parse-display` to derive `Display` and `FromStr` and it now works as I wanted. Thanks!
