### ISSUE TITLE
Serialize a HashMap as a list of tuples

### ISSUE THREAD

**Issue by jonasbb** [jonasbb/serde_with#32]
https://github.com/serde-rs/serde/issues/1476

* [x] HashMap -> List of Tuples
* [x] BTreeMap -> List of Tuples
* [x] Vec<(T, T)> -> Map

**Comment by dtolnay** [comment]
The Vec\<(K, V)\> ⟷ serde map is available in https://crates.io/crates/serde-tuple-vec-map but may make sense to reimplement in serde_with.
