### ISSUE TITLE
with_prefix! Making the module public

### ISSUE THREAD

**Issue by elpiel** [jonasbb/serde_with#327]
On a few occasions we have the same struct with the same prefix used in our applications. Currently the `with_prefix` creates a private module for serialize/deserialize and we have to do a hack in order to use the same prefix in other places  and applications.

I'm opening this issue to see how this could be improved in future version.

```rust
// re-export the prefix module!
pub mod prefix_active {
    use serde_with::with_prefix;

    pub use prefix_active::*;

    with_prefix!(prefix_active "active_");
}
```

PS: Thank you all very much for creating and maintaining this crate!

**Comment by jonasbb** [comment]
`with_prefix!` extends to a simple module ([source](https://github.com/jonasbb/serde_with/blob/42225c44e24ee9ac3a272bfaa84079ba4506f49d/src/with_prefix.rs#L103-L135)). Would it be enough for you to extend the syntax with on optional visibility qualifier in front of the module name? Something like this. The default would still be private (i.e., `pub(self)`).

```rust
with_prefix!(prefix_active "active_");                   // => mod {...}
with_prefix!(pub prefix_active "active_");               // => pub mod {...}
with_prefix!(pub(crate) prefix_active "active_");        // => pub(crate) mod {...}
with_prefix!(pub(in other_mod) prefix_active "active_"); // => pub(in other_mod) mod {...}
```

**Comment by elpiel** [comment]
I will try to make time and do the changes :yum:

**Comment by jonasbb** [comment]
Thank you :) The change shouldn't be too complicated. You can see how it works for `serde_conv!` https://github.com/jonasbb/serde_with/commit/84aecca79aaaf4c3fe40aecd144d74bb116da7ad
1-2 sentences in the documentation about this should be enough.
