### ISSUE TITLE
Add support for base64 de/encoding

### ISSUE THREAD

**Issue by jonasbb** [jonasbb/serde_with#350]
Support for base64 encoding would look similar to the existing `hex` module. One significant difference is the amount of different base64 character sets. Different character set can be supported using multiple format-like types. Custom character sets would require an approach similar to `StringWithSeparator` of a new trait or full const generics.

**Comment by kevincox** [comment]
I'm so surprised that I can't find this in the ecosystem. The hex module is great and would love to see the same for base64.

**Comment by jonasbb** [comment]
@kevincox The simple reason for it not existing is that I did not need this functionality yet and nobody showed interest in it so far. I can spend some time on it. The two important modifiers are probably character set and padding. Something like `Base64<CHARSET = Standard, const PADDING: bool = true>`. This allows shortening it to `#[serde_as(as = "Base64")]` if necessary. The `PADDING` only affects the serialization, but not the deserialization.

**Comment by kevincox** [comment]
That looks good to me.
