### ISSUE TITLE
Cannot deserialize_as types with a generic type parameter that does not have implied Deserialize bound

### ISSUE THREAD

**Issue by JonathanxD** [jonasbb/serde_with#422]
Hello, I've trying to not write my own `Deserializer` and found this crate which provides a bunch of nice features for [serde](https://serde.rs) and I've been considering using the `DefaultOnError` to have an error tolerant deserialization of enum variants, but I have a bit uncommon scenario (I think).

I have a structure close to this (a bunch of fields were omitted):

<details>
<summary> Rust Code  </summary>

```rust
use serde_derive::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Response<T> {
    pub data: ResponseData<T>
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ResponseData<T> {
    pub intent: Intent<T>
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Intent<T> {
    #[serde(rename = "name")]
    pub intent_type: IntentType<T>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(untagged)]
pub enum IntentType<T> {
    Known(Known),
    Custom(T),
    Unknown,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum Known {
    #[serde(rename = "V.A")]
    A,
    #[serde(rename = "V.B")]
    B,
}

impl<T> Default for IntentType<T> {
    fn default() -> Self {
        Self::Unknown
    }
}
```
</details>

And I've wrote these testing units:

<details>
<summary> Rust Test Code  </summary>

```rust
#[cfg(test)]
mod tests {
    use crate::*;

    #[test]
    fn serialize_tuple_test() {
        let ser = serde_json::to_string(&Response::<()> { data: ResponseData { intent: Intent { intent_type: IntentType::Known(Known::A) } } }).unwrap();
        assert_eq!(r#"{"data":{"intent":{"name":"V.A"}}}"#, ser);
    }

    #[test]
    fn deserialize_tuple_test() {
        let json = r#"{"data":{"intent":{"name":"V.A"}}}"#;
        let de: Response<()> = serde_json::from_str(json).unwrap();
        assert!(matches!(de, Response { data: ResponseData { intent: Intent { intent_type: IntentType::Known(Known::A) } } }));
    }

    #[test]
    fn serialize_custom_test() {
        #[derive(Debug, Clone, Deserialize, Serialize)]
        #[serde(rename_all = "camelCase")]
        enum Custom {
            LetsPlay
        }

        let ser = serde_json::to_string(&Response { data: ResponseData { intent: Intent { intent_type: IntentType::Custom(Custom::LetsPlay) } } }).unwrap();
        assert_eq!(r#"{"data":{"intent":{"name":"letsPlay"}}}"#, ser);
    }

    #[test]
    fn deserialize_custom_test() {
        #[derive(Debug, Clone, Deserialize, Serialize)]
        #[serde(rename_all = "camelCase")]
        enum Custom {
            LetsPlay
        }

        let json = r#"{"data":{"intent":{"name":"letsPlay"}}}"#;
        let de: Response<Custom> = serde_json::from_str(json).unwrap();
        assert!(matches!(de, Response { data: ResponseData { intent: Intent { intent_type: IntentType::Custom(Custom::LetsPlay) } } }));
    }


    #[test]
    fn deserialize_unknown_test() {
        #[derive(Debug, Clone, Deserialize, Serialize)]
        #[serde(rename_all = "camelCase")]
        enum Custom {
            LetsPlay
        }

        let json = r#"{"data":{"intent":{"name":"foobar"}}}"#;
        let de: Response<Custom> = serde_json::from_str(json).unwrap();
        assert!(matches!(de, Response { data: ResponseData { intent: Intent { intent_type: IntentType::Unknown } } }));
    }
}
```
</details>

All testes are passing, with the exception for the `deserialize_unknown_test` one, which I'm trying to solve by using [serde_as](https://docs.rs/serde_with/latest/serde_with/attr.serde_as.html), below is the modified version of `Intent<T>` with the `#[serde_as(...)]` attribute:

<details>
<summary> Intent&lt;T&gt; with serde_as  </summary>

```rust
#[serde_as]
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Intent<T> {
    #[serde_as(deserialize_as = "DefaultOnError")]
    #[serde(rename = "name")]
    pub intent_type: IntentType<T>,
}
```
</details>

However, when trying to compile, I'm getting this error:

<details>
<summary> Compilation error (bounds)  </summary>

```rust
error[E0277]: the trait bound `T: _::_serde::Deserialize<'_>` is not satisfied
   --> src/lib.rs:14:1
    |
14  | #[serde_as]
    | ^^^^^^^^^^^ the trait `_::_serde::Deserialize<'_>` is not implemented for `T`
    |
note: required because of the requirements on the impl of `_::_serde::Deserialize<'_>` for `IntentType<T>`
   --> src/lib.rs:22:24
    |
22  | #[derive(Debug, Clone, Deserialize, Serialize)]
    |                        ^^^^^^^^^^^
23  | #[serde(untagged)]
24  | pub enum IntentType<T> {
    |          ^^^^^^^^^^^^^
    = note: required because of the requirements on the impl of `DeserializeAs<'_, IntentType<T>>` for `Same`
    = note: 1 redundant requirement hidden
    = note: required because of the requirements on the impl of `DeserializeAs<'_, IntentType<T>>` for `DefaultOnError`
note: required by a bound in `As::<T>::deserialize`
   --> /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_with-1.12.0/src/lib.rs:424:12
    |
424 |         T: DeserializeAs<'de, I>,
    |            ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `As::<T>::deserialize`
    = note: this error originates in the attribute macro `serde_as` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider restricting type parameter `T`
    |
16  | pub struct Intent<T: _::_serde::Deserialize<'_>> {
    |                    ++++++++++++++++++++++++++++
```
</details>

*I've put the code and error in spoiler tags just for organization, because the code is a bit extensive*

I completely understand the reasoning behind this, in order to deserialize `IntentType<T>` I need that `T` implements `Deserialize<'de>`, but this requirement only arises when I use `serde_as`.

I think that it is because **serde** is correctly bounding the requirement for `T` to be `Deserialize<'de>` only when you actually try to deserialize it, for exemple, when I call `serde_json::from*`, if the `T` does not implement `Deserialize<'de>`, the call will fail, but if I never try to deserialize `T`, the code compiles correctly.

I've taken a look into `serde_with` code and found that it adds another attribute to the field, which is a `#[serde]` attribute with the custom deserializer set, but when `deserialize_with` is set, [serde does not requires the type](https://github.com/serde-rs/serde/blob/fb2fe409c8f7ad6c95e3096e5e9ede865c8cfb49/serde_derive/src/de.rs#L209-L218), lets say `Y` (which in this case `Y = IntentType<T>`, to avoid confusion with the `T` of `IntentType`) to implement `Deserialize<'de>` as [stated here](https://serde.rs/field-attrs.html#deserialize_with).

The current solution, at least for me, is to replace:
```rust
#[serde_as(deserialize_as = "DefaultOnError")]
```
with:
```rust
#[serde(deserialize_with = ":: serde_with :: As :: < DefaultOnError > :: deserialize", bound(deserialize = "IntentType<T>: serde::Deserialize<'de>"))]
```

With the final `Intent<T>` struct code being:

```rust
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Intent<T> {
    #[serde(rename = "name")]
    #[serde(deserialize_with = ":: serde_with :: As :: < DefaultOnError > :: deserialize", bound(deserialize = "IntentType<T>: serde::Deserialize<'de>"))]
    pub intent_type: IntentType<T>,
}
```

And now all the tests passes.

I wonder if it is possible to make `serde_as` macro to automatically generate this bound requirement when applicable (I'm not sure about other scenarios that would not require `T` to be `Deserialize<'de>`, I've met this crate today).

I would happily open a PR with a fix, but as I said, I've met this crate today, so I don't have enough context to know if applying the bound for all types is correct or if this is a corner case which requires special treatment.

**Comment by jonasbb** [comment]
You already found the reason why it doesn't work and the correct solution, namely specifying a `bound` attribute manually. You can still use `serde_as` 

```rust
#[serde_with::serde_as]
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Intent<T> {
	#[serde_as(deserialize_as = "DefaultOnError")]
    #[serde(rename = "name", bound(deserialize = "T: serde::Deserialize<'de>"))]
    pub intent_type: IntentType<T>,
}
```

Adding bounds automatically is not the right thing to do, since it depends on the conversion type and the field type which bounds you actually want. Consider something like, which wants to deserialize using `FromStr`.
```rust
#[serde_as(as = "DisplayFromStr")]
f: MyContainer<T>,
```

What do you want to put on `T` here? You could have a `MyContainer: FromStr` in which case `T: ` is correct. Maybe you want `T: FromStr` to parse those types from strings, too. But you could also require something like `T: FromHex` where you require parsing from a hexadecimal representation. There is no way to infer that, so it is better to not attempt it.

**Comment by JonathanxD** [comment]
Yes, I completely agree with you, this was my first concern about doing it "automatically", just hadn't any example to hold my *suspiciousness*.

It kinda dependents on what you put on `deserialize_as` attribute meta item, and couldn't be simply guessed (in a programmatically logical way, okay, it is, but not in a **simple** way).

I'm happy that I could've done without removing `serde_as`, it gives me a stable path to the **deserializer**, I should've just thought in another way (because attributes *just merge* one into another).

In the end, I changed the code beucase I wanted to have the unmatched string and did this:

```rust
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Intent<T> {
    #[serde(rename = "name")]
    pub intent_type: IntentType<T>,
}

#[serde_as]
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(untagged)]
pub enum IntentType<T> {
    Known(Known),
    Custom(T),
    #[serde_as(as = "DisplayFromStr")]
    Unknown(String),
}
```

And removed the `Default` impl.

It feels like I had been stuck into the problem, because I didn't knew `serde_as` was being transformed into `serde` `deserialize_with` attribute (but `cargo expand` helped a lot), which happens to not include the bound (which is correctly). I'm just thinking if there could be a way to improve the message for the user, but I'm unsure if **serde_with** or **serde** should do it.

Its probably a consideration for the future given the state of rust-lang/rust#54140.

Feel free to close the issue if you wishes, it may serve as a reference for someone, but they will find this issue through GitHub search/search engines.

Thanks for your attention.

**Comment by jonasbb** [comment]
Great that you found a solution for you :) For the future, the transformations performed by `serde_as` are all listed in the crate documentation of the `serde_as` attribute: https://docs.rs/serde_with/latest/serde_with/attr.serde_as.html.

It would be great if `serde` could provide better error messages or even just "do the right thing". However, since proc-macros only perform text replacement and run before type checking, this will not work. There is no API to ask if all trait bounds are satisfied or not. Maybe something like `rustc_on_unimplemented` could help, but there are no stabilization plans either.
