### ISSUE TITLE
Remove parse_type_from_string

### ISSUE THREAD

**Issue by TedDriggs** [jonasbb/serde_with#423]
As of 0.13.3, `darling` has added `impl FromMeta for Type` (TedDriggs/darling#172). This removes the need for the adapter, and will preserve span information in your macro outputs, which in turn will produce better errors if people give your macros bad inputs.

If there are other `syn` types that `impl Parse` and do not `impl FromMeta`, please feel free to file issues in TedDriggs/darling and I'll add those as well.

**Comment by jonasbb** [comment]
Thanks for the information. That is quite helpful. While rewriting I also noticed that before I never surfaced any error if the type parsing failed, so not only does that fix a layer of `Result`, but actually resolves an issue.

I will keep missing `FromMeta` implementations in mind.
