### ISSUE TITLE
Support for validators?

### ISSUE THREAD

**Issue by jgrund** [jonasbb/serde_with#433]
I've started looking at `serde_as` and it seems very powerful. Would there be interest in adding a set of validators that could return an error if their bounds are not held?

For instance, we could have a validator that checks ranges. A naive implementation:

```rust
pub(crate) struct CheckedRange<const MIN: usize, const MAX: usize>;

impl<'de, const MIN: usize, const MAX: usize> DeserializeAs<'de, String>
    for CheckedRange<MIN, MAX>
{
    fn deserialize_as<D>(deserializer: D) -> Result<String, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let x = String::deserialize(deserializer)?;

        let size = x.len();

        if size < MIN || size > MAX {
            return Err(serde::de::Error::invalid_length(
                size,
                &format!("a string between {MIN} and {MAX} chars inclusive").as_str(),
            ));
        }

        Ok(x)
    }
}
```

This could then be used like:

```rust
struct Foo {
    #[serde_as(as = "BTreeMap<CheckedRange<1, 15>, Same>")]
    pub bar: BTreeMap<String, Vec<String>>,
}
```

**Comment by jonasbb** [comment]
Hi, thanks for the idea. I never really thought about this. I never really needed a validation library. I do, however, know there are some. They could offer some guidance or possible validators, and maybe also provide the logic.

The way I currently envision `serde_as` mainly for converting the shape of the data between the Rust representation and how it is serialized. The way you wrote `CheckedRange` it doesn't fit in too nicely. It only works for a limited set of types. It could be extended by basically using the same implementation, but for types like `Cow<'_, str>` or `Box<str>`.
Validation also happens after deserialization, so having support for all conversions would be nice to have. So maybe it could look a bit more like this
https://github.com/jonasbb/serde_with/blob/8b5cfe9669765cca7107c3799ad7466b5ed2d603/serde_with/src/de/impls.rs#L22-L34=

**Comment by jonasbb** [comment]
I am going to close this issue, since I do not intend to work on that topic. Feel free to reach out if that topic is still of interest and you want to work on it.
