### ISSUE TITLE
Attribute macros must be before serde's Serialize/Deserialize, but not mentioned or obvious from docs

### ISSUE THREAD

**Issue by Cpapa97** [jonasbb/serde_with#440]
serde_with's derive macros don't work if they come after serde's derive macros, and it fails silently in some situations, such as with `skip_serializing_none`.

This works:
```rust
#[skip_serializing_none]
#[derive(Serialize)]
struct Foo {
    a: Option<usize>
}
```

while this won't work, and it silently fails to alter behavior:
```rust
#[derive(Serialize)]
#[skip_serializing_none]
struct Foo {
    a: Option<usize>
}
```

This isn't noted in the docs or in the user-guide, or at least wasn't noticeable and I couldn't find a mention after skimming and searching with ctrl+f.

**Comment by jonasbb** [comment]
`skip_serializing_none` works by re-writing the struct to add `skip_serializing_if` attributes. Rust always expands attribute macros in order. If `skip_serializing_none` then the `Serialize` sees the modifications, but if the order is reversed the `Serialize` implementation is generated without the `skip_serializing_if` attributes set. This is how attribute expansion works.

Where would you expect this to be documented in the user-guide? The user guide mentions this requirement for `serde_as`, but `skip_serializing_none` doesn't appear in it (yet). Both macro documentations do not mention that. It would be useful to have it mentioned there and maybe also in the crate documentation.

**Comment by jonasbb** [comment]
In #442 I added some remarks about the order. I think that should be sufficient, but I am not sure if everybody will see it.
