### ISSUE TITLE
Why does the nested field have to be a string?

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [jonasbb/serde_with#441]
I noticed the following:

https://docs.rs/serde_with/1.9.4/serde_with/json/nested/index.html

```
#[derive(Deserialize, Serialize)]
struct A {
    #[serde(with = "serde_with::json::nested")]
    other_struct: B,
}
#[derive(Deserialize, Serialize)]
struct B {
    value: usize,
}

let v: A = serde_json::from_str(r#"{"other_struct":"{\"value\":5}"}"#).unwrap();  // This is a string not a truly nested object
```

The "other_struct" there is given as a string value which is itself a JSON object.

However, in practice, you'd normally receive the nested field as a JSON object not as a string.

In other words, you are deserialising this:

`{"other_struct":"{\"value\":5}"}`

But I want to deserialise this:

`{"other_struct":{"value":5}}`

Is it possible?

**Comment by jonasbb** [comment]
It seems like you are looking for `RawValue` from `serde_json`. This crate has nothing similar.

**Comment by SpaceMonkeyForever** [comment]
Not sure what you mean? I managed to achieve what I want by simply not having an attribute. 'serde' is able to deserialise nested JSON just fine

**Comment by jonasbb** [comment]
Sorry, the `RawValue` suggestion is not useful. I didn't read the code snippet too careful.

From time to time, I see that people want to use `serde_with::json::nested` when they want no attribute at all. I never had the chance to ask: Is there something in the documentation which makes you believe you need the attribute? serde does the right thing be default, so I'm not sure how people end up finding this crate and `json::nested`.

**Comment by SpaceMonkeyForever** [comment]
In my particular case, I tried first without the attribute and it didn't
work but it was for a different reason and because it was failing inside an
async function, it did not panic and print the error so I could see what
went wrong so I wrongly assumed it's because of nesting since that was the
more likely cause (turned out that it was a u8 field that was too small and
should be u64).

This is a beginner mistake because I'm still learning Rust. Altho I should
have known from experience with other platforms that if an error is thrown
inside a Task/Future, it doesn't always propagate back to the caller
(depending on the platform, I think).
