### ISSUE TITLE
Deserialize true/false from 1/0

### ISSUE THREAD

**Issue by TonalidadeHidrica** [jonasbb/serde_with#456]
It'd be useful to have `bool_from_int` shown in serde-rs/serde#1344.

**Comment by jonasbb** [comment]
Hi, thanks for the feedback. Could you please expand more on what exactly your needs are? The linked issue only mentions parsing from 0/1. But there are many variants possible. For integers you could also allow all numbers and check for `!= 0`. Both cases can be covered with [`serde_with::formats::Strictness`](https://docs.rs/serde_with/latest/serde_with/formats/trait.Strictness.html). It can be modelled as `BoolFromInt<S: Strictness>`.

Do you also require parsing strings to bools, something like "t" or "f"?

**Comment by piavgh** [comment]
@jonasbb : after adding BoolFromInt, I can not use parameter `true` or `false` anymore (only 0 or 1 works with `bool` param now)

What should I do to support both ways?

**Comment by jonasbb** [comment]
@piavgh Please open new issues for help requests and don't post on old topics with unrelated problems.
You can make use of [`PickFirst`](https://docs.rs/serde_with/latest/serde_with/struct.PickFirst.html), e.g., `PickFirst<_, BoolFromInt>`, but since you don't provide any details of which format you target or what you need for serialization I cannot help you more.

**Comment by piavgh** [comment]
> @piavgh Please open new issues for help requests and don't post on old topics with unrelated problems. You can make use of [`PickFirst`](https://docs.rs/serde_with/latest/serde_with/struct.PickFirst.html), e.g., `PickFirst<(_, BoolFromInt)>`, but since you don't provide any details of which format you target or what you need for serialization I cannot help you more.

Thanks, I created a new issue here https://github.com/jonasbb/serde_with/issues/631
