### ISSUE TITLE
Render source errors when deriving `DeserializeFromStr`

### ISSUE THREAD

**Issue by Veetaha** [jonasbb/serde_with#458]
If the error returned by `FromStr` implementation contains source errors chain, they should be rendered into the custom serde error.
As for now, we are using our own proc macro instead of `derive(serde_with:DeserializeFromStr)` that returns the following impl:

```rust
quote! {
    impl<'de> #serde::Deserialize<'de> for #ty_ident {
        fn deserialize<D>(deserializer: D) -> #p::Result<Self, D::Error>
        where
            D: #serde::Deserializer<'de>,
        {
            use #stdx::prelude::*;

            #p::String::deserialize(deserializer)?
                .parse::<Self>()
                .map_err(|err| <D::Error as #serde::de::Error>::custom(err.display_chain()))
        }
    }
}
```

Where `stdx` is our private crate that adds `display_chain()` method returning an object which renders all source errors chain in its `Display` impl. The rendering logic there was based on `anyhow impl` like and outputs messages of this form:

```
Error: Failed to read instrs from ./path/to/instrs.json

Caused by:
    No such file or directory (os error 2)
```

# Elegy of an Idealist

Ideally, `serde::de::Error` should have a constructor that accepts a `dyn std::error::Error` to capture its `source()` errors transparently, but alas it allows only using `custom(impl Display)` method that makes us do all the rendering upfront...
https://github.com/serde-rs/serde/issues/2222

**Comment by jonasbb** [comment]
I am unsure what you are asking here. `DeserializeFromStr` only works if your error type implements `Display`. This is documented.
> Additionally, FromStr::Err must implement [Display](https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html) as otherwise you will see a rather unhelpful error message

The reason for that is that the only way to create a custom error is the [`custom` method](https://docs.rs/serde/latest/serde/de/trait.Error.html#tymethod.custom) which requires a type implementing `Display`.
 As such, I am unsure what `display_chain` would do on a `Display` type.

You can of course use the `DeserializeFromStr` from this crate if you simply return `err.display_chain()` from your `FromStr` implementation.

**Comment by Veetaha** [comment]
@jonasbb I think https://github.com/serde-rs/serde/issues/2222 best describes the problem.

I think it would be best if `serde_with` provided an impl of `DeserializeFromStr where FromStr::Err: std::error::Error`, because in 99% of the cases it will be true. And when you render an `std::error::Error`, you don't want to do it just by `format!("{}", error)`. You need to iterate over `error.source()` and include the messages from all source errors too.

**Comment by jonasbb** [comment]
I am uncertain if a new derive using `std::error::Error` will be that useful in general. `DisplayFromStr` and its older version are among the most used parts of the crate, yet so far, the `Display` bound didn't come up as a problem. I think that is for a couple of reasons:
1. Every `std::error::Error` must implement `Display`, thus the `Display` bound is more general.
2. Many error types used in `FromStr` do not have any sources to iterate over. They are often unit structs or unit enums.

A non-insignificant part of implementations uses types which are not `Error` but are `Display`, like `&str`, `String`, or `anyhow::Error`.
If you want to use `DeserializeFromStr` you are better off changing the `Display` implementation of your `Err` type to print all source errors too.
