### ISSUE TITLE
Non string values in attribute macro

### ISSUE THREAD

**Issue by ModProg** [jonasbb/serde_with#533]
As it is now possible to have any tokens in attribute macros without needing to wrap them in strings, it would make sense to migrate to something like this:

```rs
#[serde_as(as=SomeThing)]
```

These changes were made e.g. in `clap` and will happen in `derive_where` with the next release. In the case of `serde_with` this could even be done in a backward compatible way allowing both strings and plain types.

**Comment by jonasbb** [comment]
Hi, thanks for the idea. I did consider that a bit when creating the macros and I think there is some value in staying close to the serde derives, i.e., mostly use strings. Enabling this as a secondary optional syntax is probably ok, at worst there might be a little confusion whether there is a semantic difference.

I am unsure how much effort this would be. `darling` would necessarily need to support arbitrary tokens for this to work. And I `syn` makes this a bit harder than working with strings, for example `syn::Meta` is quite constrained.

Does this change have any benefits regarding rust error messages or IDE integration?

**Comment by ModProg** [comment]
> Does this change have any benefits regarding rust error messages or IDE integration?

IIRC I was able to trigger a code-action to import a type on a macro using this syntax. But I'm not 100% sure and would need to check where that was.

**Comment by jonasbb** [comment]
For now, I would rather not pursue this. Neither `syn` nor `darling` is currently equipped to handle unquoted attributes well. As such, it is difficult to support for `serde_with`. The value of removing quotes is unclear to me. If there is a clear benefit or if the dependencies make support much simpler than it can be reconsidered. But until then it seems like a lot of effort for an unclear but limited win.
