### ISSUE TITLE
Using serde_with::rust::sets_last_value_wins with serde_as notation

### ISSUE THREAD

**Issue by seowalex** [jonasbb/serde_with#534]
I would like to use `serde_with::rust::sets_last_value_wins` with the `serde_as` notation, but that does not seem to be possible. Am I missing something?

**Comment by jonasbb** [comment]
Hi, thanks for raising the issue. That is indeed currently not possible, as this module and the related ones were never updated. I don't think there is any technical challenge here, just a bit of busy work.
This part of the guide contains the relevant part for converting. https://docs.rs/serde_with/latest/serde_with/guide/serde_as/index.html#using-serde_as-on-types-without-serializeas-and-serialize-implementations
Additionally, the documentation would need to be updated too.

If you need this urgently, you can also create a conversion type in your codebase. You can follow the guide and replace `MODULE` with `serde_with::rust::sets_last_value_wins`.

**Comment by seowalex** [comment]
I am interested in implementing this, but what would the syntax look like in the `serde_as` notation?

**Comment by jonasbb** [comment]
You need a new type and implement the traits for it (see link).
```rust
pub struct SetLastValueWins<V>(PhantomData<V>);
```

You should then be able to use it like any other `serde_as` attribute:
```rust
#[serde_as(as = "SetLastValueWins<_>")]
BTreeSet<u32>,
```

**Comment by seowalex** [comment]
What if instead of `SetLastValueWins<_>`, I want to use something like `SetLastValueWins<PickFirst<(_, ...)>>`? The conversion type I created doesn't seem to be able to handle that.

**Comment by jonasbb** [comment]
In this case, you will need to adapt the existing code a bit. The values need to be transformed, since you cannot directly serialize a `SerializeAs`.  You might want to look at the documentation of the traits: https://docs.rs/serde_with/2.1.0/serde_with/trait.SerializeAs.html#differences-to-serialize especially how the `SerializeAsWrap` is working.
