### ISSUE TITLE
Add `skip_serializing_empty` macro

### ISSUE THREAD

**Issue by ibotty** [jonasbb/serde_with#537]
It would be great to allow skipping (de)serializing an empty vector.

E.g. for `struct A { a: Vec<u8>, }` the JSON `{}` would get deserialized to `A{ a: [] }`.

**Comment by jonasbb** [comment]
This question is quite vague and lacks details, but I will try my best to give some hints.
Adding a macro `skip_serializing_empty` which works like `skip_serializing_none` will not happen. There is no generic way to check if something is empty, and specializing it only on the types provided in `std` feels too limiting.

Skipping the serialization of empty vectors is already possible with the `serde_derive` macros. Skipping deserialization is a nonsensical operation and not supported. It looks like you are looking for a default value if a field is missing. You should look at the [field attributes provided by `serde_derive`](https://serde.rs/field-attrs.html), especially `skip_serializing_if` and `default`

If you want to apply field attributes automatically to many fields, you can use the [`serde_with::apply`](https://docs.rs/serde_with/latest/serde_with/attr.apply.html) macro.

**Comment by ibotty** [comment]
Sorry for not being clear.  I understand your reasoning and will try to use `serde_with::apply`.  Thank you for pointing me in this direction.

**Comment by fawdlstty** [comment]
@jonasbb Hello author, I have encountered the same problem as the issue launcher. Are you interested in adding the above macro? For me, just only on the types provided in `std` would be a great help

**Comment by fawdlstty** [comment]
<img width="1382" height="362" alt="Image" src="https://github.com/user-attachments/assets/39c9b063-5e79-4954-9e88-2c840b17d9ba" />
<img width="969" height="389" alt="Image" src="https://github.com/user-attachments/assets/fbda6e32-f1fc-4f1a-9c1b-94c00c8eed8b" />
@jonasbb yes, it's not work

**Comment by fawdlstty** [comment]
Please forgive me for not including Vec in the structure, this is just an example to prove that it doesn't work
