### ISSUE TITLE
Enable std/alloc without other features like chrono

### ISSUE THREAD

**Issue by M1cha** [jonasbb/serde_with#550]
If you're fixed to an incompatible version of chrono or just want to save on code size, you don't really want any of that enabled. You might still want to use the utils for (de-)serializing things like `Vec`s though.

**Comment by jonasbb** [comment]
Is is already the case. The only things enabled by alloc and std are the features of the same name in serde. For the öffnet creates the feature uses "?" to not pull new dependencies in. 

https://github.com/jonasbb/serde_with/blob/a079e9c1e5a60534244f0d60fa491f941bdf0bd8/serde_with/Cargo.toml#L29-L48

**Comment by M1cha** [comment]
Unfortunately this doesn't seem to be working though.
A binary with thise dependency section:
```
[dependencies]
chrono = "= 0.4.19"
serde_with = { version = "2.2", default_features = false, features = ["std"] }
```

fails to compile with:
```
error: failed to select a version for `chrono`.
    ... required by package `serde_with v2.2.0`
    ... which satisfies dependency `serde_with = "^2.2"` (locked to 2.2.0) of package `tmp v0.1.0 (/tmp/tmp)`
versions that meet the requirements `^0.4.20` are: 0.4.23, 0.4.22, 0.4.21, 0.4.20

all possible versions conflict with previously selected packages.

  previously selected package `chrono v0.4.19`
    ... which satisfies dependency `chrono = "=0.4.19"` (locked to 0.4.19) of package `tmp v0.1.0 (/tmp/tmp)`

failed to select a version for `chrono` which could resolve this conflict
```

**Comment by jonasbb** [comment]
This is caused by https://github.com/rust-lang/cargo/issues/10801 and pinning chrono to a single version. Pinning to a specific version works very poorly, and you will run into more problems like this. If you only add `serde_with` as a dependency, you will see that chrono will not be compiled.

You should drop the version pinning of chrono. Alternatively, you can use a different version of `serde_with` like <=2.0.0.

**Comment by M1cha** [comment]
I can't unpin chrono right now due to [this issue](https://github.com/chronotope/chrono/issues/834).
Thanks for the hint about Cargo.lock.

`serde_with` 2.0 seems to work just fine.
Even though this situation is not ideal, it's not caused by serde_with directly and thus not something that can be fixed by this project.

Thanks a lot for the clarification.
