### ISSUE TITLE
How to combine `double_option` and `serde_as`?

### ISSUE THREAD

**Issue by grgi** [jonasbb/serde_with#553]
I found the nice implementation of `serde_with::rust::double_option` but this works only for pure `serde`, right? Is there a corresponding implementation for `DeserializeAs`?  E.g. something like this:

```rust
pub struct DoubleOption<T>(PhantomData<T>);

impl<'de, T, U> DeserializeAs<'de, Option<Option<T>>> for DoubleOption<U>
where
    U: DeserializeAs<'de, T>,
{
    ...
}

#[serde_as]
#[derive(Debug, Deserialize)]
pub struct Foo {
    #[serde_as(deserialize_as = "DoubleOption<DisplayFromStr>")]
    pub foo: Option<Option<u8>>,
}
```

Unfortunately, if using an `OptionVisitor` like in the implementation of  `DeserializeAs` for `Option<T>`, I get a panic about missing fields.

Is there another possibility?

**Comment by jonasbb** [comment]
You can see a detailed answer why this doesn't work in this answer: https://github.com/jonasbb/serde_with/issues/546#issuecomment-1420669533
The short summary is that a `DoubleOption` type like you suggest allows nonsensical situations and the best way is creating your own `double_option_display_from_str` module.

**Comment by grgi** [comment]
Sorry, somehow I must have overlooked it. Thanks a lot!
