### ISSUE TITLE
Add serialize/deserialize adapters for chrono's Duration

### ISSUE THREAD

**Issue by jonasbb** [jonasbb/serde_with#56]
Similar issue exists here: https://github.com/chronotope/chrono/issues/117

**Comment by Exr0n** [comment]
Just wondering, any updates on this?

**Comment by jonasbb** [comment]
Unfortunately no update yet. However, recently I made some progress for the std Duration (for example [here](https://github.com/jonasbb/serde_with/blob/cce7208b6a47d5d2249ed03ee98253d0938abc34/src/ser/impls.rs#L334-L380)). That should translate mostly to the chrono types too

**Comment by jonasbb** [comment]
The latests version (1.5.0-alpha.2) can convert `Durations` into seconds, e.g., [`serde_with::DurationSeconds`](https://docs.rs/serde_with/1.5.0-alpha.2/serde_with/struct.DurationSeconds.html).
This will likely get extended for milliseconds and similar. Then for both `std::time::Duration` and `chrono::Duration`.
