### ISSUE TITLE
Better Document behavior of DurationSeconds

### ISSUE THREAD

**Issue by xiaoas** [jonasbb/serde_with#575]
The following code won't compile:
```rust
#[serde_as]
#[derive(Debug, Serialize, Deserialize)]
pub struct Request {
    #[serde_as(as = "DurationSeconds")]
    pub span: chrono::Duration,
}
```
The code snippet is very similiar to the `Foo` struct in [advanced serde_as usage](https://docs.rs/serde_with/latest/serde_with/#advanced-serde_as-usage), difference is that Duration has been changed to a chrono duration.

The resulting compile error is bit hard-to-read:
```
error[E0277]: the trait bound `DurationSeconds: DeserializeAs<'_, chrono::Duration>` is not satisfied
   --> src/service/diff_abn_report.rs:13:1
    |
13  |   #[serde_as]
    |   ^----------
    |   |
    |  _in this procedural macro expansion
    | |
14  | | #[derive(Debug, Serialize, Deserialize)]
    | |______________________________________^ the trait `DeserializeAs<'_, chrono::Duration>` is not implemented for `DurationSeconds`
    |
    = help: the following other types implement trait `DeserializeAs<'de, T>`:
              <DurationSeconds as DeserializeAs<'de, serde_with::utils::duration::DurationSigned>>
              <DurationSeconds as DeserializeAs<'de, std::time::Duration>>
note: required by a bound in `serde_with::de::<impl serde_with::As<T>>::deserialize`
```

# Suggestion
IMO We should better document that user should explicitly annotate `DurationSeconds` with `i64`:
```rust
#[serde_as]
#[derive(Debug, Serialize, Deserialize)]
pub struct Request {
    #[serde_as(as = "DurationSeconds<i64>")]
                                 // ^^^^^
    pub span: chrono::Duration,
}
```
On this page https://docs.rs/serde_with/latest/serde_with/struct.DurationSeconds.html

**Comment by jonasbb** [comment]
Hi, thanks for the suggestion. Do you have a concrete improvement in mind? All the examples with `chrono::Duration` on the `DurationSeconds` page use a more explicitly annotated `DurationSeconds`. The comparison table also lists that `chrono::Duration` is incompatible with the default format of `u64`. 

```rust
use chrono::Duration;

#[serde_as]
#[derive(Deserialize, Serialize)]
struct Durations {
    #[serde_as(as = "DurationSeconds<i64>")]
    d_i64: Duration,
    #[serde_as(as = "DurationSeconds<f64>")]
    d_f64: Duration,
    #[serde_as(as = "DurationSeconds<String>")]
    d_string: Duration,
};
```

The example under "Advanced serde_as usage" used `std::time::Duration`. That is not directly obvious, since the import is hidden.

**Comment by xiaoas** [comment]
imo
- The example on the crate main page should use the explicit annotation, a example for chrono::Duration might be helpful as well.
- The DurationSeconds page should have a example detailing using `DurationSeconds<i64>` on `std::time::Duration`, or using `DurationSeconds<u64>` on `chrono::Duration` are both incorrect.

What do you think?

**Comment by jonasbb** [comment]
I made some changes in #576. I unhid the `Duration` import. I don't like the idea of showing wrong examples. I added some explanatory sentences and added some emphasis to the `FORMAT` support table for `DurationSeconds`/`TimestampSeconds`.
