### ISSUE TITLE
applying serde_as to whole struct.

### ISSUE THREAD

**Issue by blueforesticarus** [jonasbb/serde_with#598]
I have many serde_as transforms that act on types that themselves implement serialize/de-serialize, and wrap them in some way. This leads to having to use serde_as in the same way on every field of that type. It would be more convenient to apply the transform to the struct itself. 

ie. instead of 
```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageId(pub String);
impl SurrealLink for MessageId {
    const TABLE: &'static str = "message";
}

#[serde_as]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    #[serde_as(as = "SurrealAsLink")]
    pub id: MessageId,
    pub channel: ChannelId,

    pub sender: SenderId,
    pub date: DateTime<Utc>,
    pub links: Vec<Link>,
}
```

we'd have
```rust
#[serde_as(as = "SurrealAsLink")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageId(pub String);
impl SurrealLink for MessageId {
    const TABLE: &'static str = "message";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub id: MessageId,
    pub channel: ChannelId,

    pub sender: SenderId,
    pub date: DateTime<Utc>,
    pub links: Vec<Link>,
}
```

**Comment by blueforesticarus** [comment]
This probably would have big implementation problems, since we can't have 2 implementation of de-serialize on MesssageId

**Comment by jonasbb** [comment]
If you end up in a situation where you need to apply `serde_as` every time you use a type, that sounds to me like you should fix the implementations of `Serialize` and `Deserialize`. If they don't solve your needs, they seem like a hindrance.

You didn't provide any information about what data format you use, how the serialized data looks like, or how you defined `SurrealAsLink`, so I cannot help you beyond some basic hints.
You can use `serde_as` on newtype structs. You must place the `serde_as` attribute before the struct *and* the field you want to modify, like
```rust
#[serde_with::serde_as]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageId(#[serde_as(as = "SurrealAsLink")] pub String);
```
Changes to `SurrealAsLink` might be needed. I cannot tell how you defined it. If that is not good enough, you can always handwrite the implementations. Given that you already have the `SerializeAs` implementation, that should be trivial.

**Comment by blueforesticarus** [comment]
The new-type method you describe was the same solution I came to, but in my case these are business logic types; It feels wrong to adapt them for serialization instead of adapting serialization to them.
 
I agree that really MessageId should have its one impl of Serialize and Deserialize. The issue, is that I have many such structs with the same pattern. Specifically: MessageId should be serialized as `("message", **Self)`.  where `**Self` is serialization serde would have derived.

**Comment by jonasbb** [comment]
You have an existing implementation like
```rust
impl SerializeAs<MessageId> for SurrealAsLink {
    fn serialize_as<S: Serializer>(value: &MessageId, serializer: S) -> {
        //...
   } 
}
```

That is what makes your attribute work. 
```rust
#[serde_as(as = "SurrealAsLink")]
pub id: MessageId,
```

Why don't you change that into this. That way your MessageId has the correct behavior by default. It is only some re-naming that need to be done.

```rust
impl Serialize for MessageId {
    fn serialize<S: Serializer>(&self, serializer: S) -> {
        //...
   } 
}
```

**Comment by blueforesticarus** [comment]
Because SurrealAsLink is implemented generically.  https://github.com/blueforesticarus/goontunes2/blob/9be5368091ab55f1850d2ccda9dfbb5087ce425b/src/database.rs#LL16C1-L84C2

**Comment by jonasbb** [comment]
The fact that SurrealAsLink is generic should not be a problem in performing the transformation I described above.
I cannot support serde_as on a struct since serde itself does not support it. The serde_as boils down to a serde(with = "") but that only exists for fields and not as a container attribute.

Maybe you can build something with the from/into container attributes. https://serde.rs/container-attrs.html#from
