### ISSUE TITLE
Performance of Bytes with bincode

### ISSUE THREAD

**Issue by ironspecs** [jonasbb/serde_with#604]
Is there something that I'm missing?  I changed my struct using plain serde to use raw bytes, and got a notable decrease in performance.  As expected.

I tried out serde_bytes.  Then tried it with "alloc" enabled so it applies to Box<[u8]> and Vec<u8>.  Still no improvement in performance.

I tried out serde_with.  Again, no improvement in performance.  I've gone through the available docs of all three packages, and I've started going into the code too.

Is there a step here that I'm missing?

<img width="1046" alt="image" src="https://github.com/jonasbb/serde_with/assets/4154804/c2af80d2-68aa-409f-9d41-87def7d58f7a">

Note the time to run. I'm just writing a short struct as bytes with one of the values of the struct as a key.  I'm writing 400 of these to a file in each test, and then reading them back in.

<img width="410" alt="image" src="https://github.com/jonasbb/serde_with/assets/4154804/ab54c34d-6240-4b91-b817-05242bae68cc">

<img width="413" alt="image" src="https://github.com/jonasbb/serde_with/assets/4154804/98e27781-0fe6-4a71-9e17-3a104daff9a4">

**Comment by jonasbb** [comment]
> I changed my struct using plain serde to use raw bytes, and got a notable decrease in performance. As expected.

This is quite unexpected to me. Using `serde_bytes` or `serde_with::Bytes` should result in a (small) speedup or have no impact on performance. In your picture it looks like this is a 4 time performance decrease. I think there might be more going on here.

I cannot help you with the performance of bincode. If it reacts badly to the bytes annotation you should raise an issue with them.

If you see a performance difference between  `serde_bytes` and `serde_with::Bytes` then please let me now. But it sounds like they behave equally for you.
