### ISSUE TITLE
Combine `DisplayFromStr` and `NoneAsEmptyString`

### ISSUE THREAD

**Issue by kevinheavey** [jonasbb/serde_with#605]
I'm parsing JSON where number fields either look like `"1234"` or `""`, and I would like to parse these as `Option<u32>`, so I would appear to need both `DisplayFromStr` and `NoneAsEmptyString`. There's no way to use both of these on the same field, right?

**Comment by jonasbb** [comment]
That is the current behavior of `NoneAsEmptyString`. There is a mistake in the text documentation, saying that it uses `AsRef<str>`. But in reality, the `SerializeAs` implementation uses `Display`. Deserialization is correctly documented as using `FromStr`.

```rust
#[serde_as]
#[derive(serde::Serialize, serde::Deserialize, Debug)]
struct S {
    #[serde_as(as = "NoneAsEmptyString")]
    a: Option<u32>,
    #[serde_as(as = "NoneAsEmptyString")]
    b: Option<u32>,
}

let j = serde_json::to_string_pretty(&S {
    a: None,
    b: Some(123),
}).unwrap();

println!("{j}");

let s: S = serde_json::from_str(&j).unwrap();
dbg!(s);
```
[Rustexplorer](https://www.rustexplorer.com/b/io08x8)
