### ISSUE TITLE
Document ordering of DisplayFromStr invocation

### ISSUE THREAD

**Issue by FlareFlo** [jonasbb/serde_with#606]
The docs for [DisplayFromStr](https://docs.rs/serde_with/latest/serde_with/struct.DisplayFromStr.html) do not mention that ordering for the attribute macro must come before derive macro, because the `serde_as` attribute otherwise does not work. 

Proposal:

- Mention ordering  of macros in example and documented block above

**Comment by jonasbb** [comment]
This is a recurring problem, but I am not aware how to build diagnostics or about the documentation. It is already mentioned in the README, on the first page of the crate documentation, in the [`#[serde_as]`](https://docs.rs/serde_with/latest/serde_with/attr.serde_as.html) documentation, and in user guide under ["Switching from serde’s with to `serde_as`"](https://docs.rs/serde_with/latest/serde_with/guide/serde_as/index.html#switching-from-serdes-with-to-serde_as).

Maybe these existing places can be improved. I am happy to hear feedback about them. I don't think explaining the Rust macro system belongs into the documentation for the `DisplayFromStr` type. Like this, every conversion type would need to duplicate this documentation.

**Comment by FlareFlo** [comment]
> This is a recurring problem, but I am not aware how to build diagnostics into the macro or about the documentation. It is already mentioned in the README, on the first page of the crate documentation, in the [`#[serde_as]`](https://docs.rs/serde_with/latest/serde_with/attr.serde_as.html) documentation, and in user guide under ["Switching from serde’s with to `serde_as`"](https://docs.rs/serde_with/latest/serde_with/guide/serde_as/index.html#switching-from-serdes-with-to-serde_as).
> 
> Maybe these existing places can be improved. I am happy to hear feedback about them. I don't think explaining the Rust macro system belongs into the documentation for the `DisplayFromStr` type. Like this, every conversion type would need to duplicate this documentation.

I unfortunately directly jumped to the docs for `DisplayFromStr`, as i was recommended `serde_as` by a friend and did not consider such caveats as a possibility.

**Comment by jonasbb** [comment]
Since there is nothing action actionable right now, I close this. If you have suggestions on how to improve the existing places in the documentation, please let me know.
