### ISSUE TITLE
Hex with leading 0x

### ISSUE THREAD

**Issue by kevinheavey** [jonasbb/serde_with#615]
I'd like to deserialize hex bytes that look like this: `0x48656c6c6f20576f726c6421`. There's no support for this currently, right?

**Comment by jonasbb** [comment]
This is not currently supported. The `hex` crate does not have support for it. What `serde_with` does is only a small wrapper around `hex` to make it work with `serde`. Supporting prefixes does have some overhead and complicates the code, which is why it is not supported.
