### ISSUE TITLE
Use custom base64 alphabet?

### ISSUE THREAD

**Issue by Berrysoft** [jonasbb/serde_with#616]
The trait `Alphabet` are marked as sealed, which means I cannot use a custom alphabet. Would you consider removing this limitation?

**Comment by jonasbb** [comment]
This was intentionally limited in v3. The PR #543 has some more details. In v2, the trait was implementable. This means that any major updates to the `base64` crate automatically become breaking changes for `serde_with` too. Before merging the PR I searched for users of custom alphabets and could not identify any.

Why do you need this limitation removed? Could you please describe your use case and how many new alphabets you require? If it is just a single new one, that is better added as a new constant in this crate.

**Comment by Berrysoft** [comment]
I'm writing a client for a private protocol, and it uses a custom alphabet. I haven't found such alphabet elsewhere, and it's not a standard alphabet or a documented one.

Anyway, thanks for your quick reply!
