### ISSUE TITLE
DeserializeFromStr shold accept () as Err

### ISSUE THREAD

**Issue by nagisakuya** [jonasbb/serde_with#647]
```
#[derive(DeserializeFromStr)]
pub struct Hoge{
    data: u8
}

impl FromStr for Hoge {
    type Err = ();
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if let Ok(o) = s.parse() {
            Ok(o)
        } else {
            Err(())
        }
    }
}
```

This code dosen't work due to

```
error[E0277]: `()` doesn't implement `std::fmt::Display`
```

I guess inside of derive, Error is consumed by some reason. 
In my opinion, Error from FromStr should return to outside of desilialize function.

**Comment by jonasbb** [comment]
> I guess inside of derive, Error is consumed by some reason.
> In my opinion, Error from FromStr should return to outside of desilialize function.

That is exactly what is going on. The `Deserialize` implementation consists of the single deserialize function, that returns a `Result<Self, D::Err>`. That means the error type is defined by the `Deserializer`, i.e., serde_json or serde_yaml. The only way to generate the error type is using the custom function. https://docs.rs/serde/1.0.188/serde/de/trait.Error.html#tymethod.custom This is where the `Display` requirement comes from. The way rust generics work, there is no way to write `T: Display OR ()`.
