### ISSUE TITLE
Question about minimum serde version

### ISSUE THREAD

**Issue by banool** [jonasbb/serde_with#651]
Hey hey!

I see that currently `serde_with` requires a minimum serde version of `1.0.157`. I wonder if any earlier version would work or if there is some feature you need from that version onward?

I ask because I have a codebase which is unfortunately stuck on `1.0.149` and I want to use a crate that depends on `serde_with`.

Thanks!

**Comment by jonasbb** [comment]
Version 1.0.49 is already 5 years old. I am not sure any version of serde_with ever supported that. serde does add new API surfaces occasionally, and that is used. Supporting 1.0.49 is not possible. The last bump was to force serde to use syn v2. But this PR https://github.com/jonasbb/serde_with/pull/588 bumps the dependency to fix the minimal version specified, and that requires 1.0.139. So my best guess is anything under 1.0.139 cannot be supported right now, but it might be higher.

**Comment by banool** [comment]
Oh my sorry, I meant 1.0.149, my mistake.

**Comment by banool** [comment]
I can test this btw, this week I'll try pinning the version to 1.0.149 to see if it builds.

**Comment by banool** [comment]
PR to decrease the version: https://github.com/jonasbb/serde_with/pull/653/. Everything seems to pass.

**Comment by jonasbb** [comment]
PR is merged

**Comment by banool** [comment]
Could you release a new version of the crate so this change gets picked up?
