### ISSUE TITLE
Serialize enum without tags

### ISSUE THREAD

**Issue by benjamin-bergia** [jonasbb/serde_with#659]
Sorry if I missed this somewhere in the doc but is there simple way to drop the tag when serializing an enum?

**Comment by jonasbb** [comment]
Are you perhaps looking for [`serde(untagged)`](https://serde.rs/container-attrs.html#untagged)? That is one of the standard enum serialization ways in serde: https://serde.rs/enum-representations.html.
There is nothing like that currently in this crate. I think writing something for dropping the tags during serialization should be possible. You wrap the `Serializer` and forward all calls to `serialize_*_variant` to `serialize_*_struct`. It will no longer be possible to deserialize the struct.

**Comment by benjamin-bergia** [comment]
Thank you
