### ISSUE TITLE
Use without macros

### ISSUE THREAD

**Issue by jbirnick** [jonasbb/serde_with#753]
Hey, let 's say I have a `hashmap : HashMap<i8,u32>`, and I want to serialize this as a sequence of tuples `(i8,u32)`. How can I do that _without_ creating an extra struct and using an attribute macro like `serde_as`?

I just want to do that sort of in-place on the hashmap variable, I don't want the hashmap to be contained in a "parent struct".

Any help is very much appreciated!

**Comment by jonasbb** [comment]
Answered in #754
