### ISSUE TITLE
Hashbrown 0.15.0

### ISSUE THREAD

**Issue by takaomag** [jonasbb/serde_with#787]
Yesterday, hashbrown 0.15.0 is released.

Currently, serde_with has `hashbrown_0_14` feature which supports only 0.14.
New `hashbrown_0_15` feature or `hashbrown` feature for both versions should be added?

**Comment by jonasbb** [comment]
Hi and thanks for the information. The correct way to go about it is to add a new optional dependency and feature. Both named `hashbrown_0_15`. It can be mostly a copy of the existing code.
https://github.com/jonasbb/serde_with/blob/f1b79f27cac7545513c4f14f7c295db2b843cc4f/serde_with/Cargo.toml#L70-L75
The next steps are to copy the implementations that exist for `hashbrown_0_14` and copy them over too. The implementations for map and set types is spread throughout the code base, but can usually be found by looking at the type names or imports.
https://github.com/jonasbb/serde_with/blob/f1b79f27cac7545513c4f14f7c295db2b843cc4f/serde_with/src/de/impls.rs#L3-L4

**Comment by takaomag** [comment]
Thanks!
