### ISSUE TITLE
Question: is there an inverse of `KeyValueMap`?

### ISSUE THREAD

**Issue by cyqsimon** [jonasbb/serde_with#792]
`KeyValueMap` serializes a `Vec<T>` into a map, but I'm looking for the inverse.

Is there something that serializes a `*Map<K, V>` into a list, where `K` becomes a field in `V`, similar to [internally tagged enum representation](https://serde.rs/container-attrs.html#tag)?

## E.g.

Given:

```rust
struct AsList {
    items: HashMap<String, Ty>,
}
struct Ty {
    foo: usize,
    bar: usize,
}
```

I would like to have this:

```rust
AsList {
    items: [
        ("a".to_owned(), Ty { foo: 0, bar: 1 }),
    ].into(),
}
```

... serialize into this:

```json
{
  "items": [
    {
      "key": "a",
      "foo": 0,
      "bar": 1
    }
  ]
}
```

**Comment by jonasbb** [comment]
No, there is nothing like that in the crate. It seems possible to implement this for a specific case.

As a general implementation, I see two problems right now. You somehow need to make the `key` part configurable. This is not a problem for a specific implementation. However, to make it general, you can't simply pass the string as generic type parameter, as const generics does not cover strings and `adt_const_params` is not anywhere close to implementation.

In the example implementation below I used `serde(flatten)` to implement it. However, there are some downsides with `flatten`, like extra buffering, and that the added `key` could interfere with deserialization.

<details>
<summary>Example implementation</summary>

```rust
use serde::*;
use std::collections::HashMap;

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(into = "AsListSerDe", from = "AsListSerDe")]
struct AsList {
    items: HashMap<String, Ty>,
}

#[derive(Debug, Serialize, Deserialize)]
struct AsListSerDe {
    items: Vec<FlatKeyValue<String, Ty>>,
}

impl From<AsList> for AsListSerDe {
    fn from(al: AsList) -> Self {
        Self {
            items: al
                .items
                .into_iter()
                .map(|(key, value)| FlatKeyValue { key, value })
                .collect(),
        }
    }
}

impl From<AsListSerDe> for AsList {
    fn from(al: AsListSerDe) -> Self {
        Self {
            items: al
                .items
                .into_iter()
                .map(|FlatKeyValue { key, value }| (key, value))
                .collect(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone)]
struct Ty {
    foo: usize,
    bar: usize,
}

#[derive(Serialize, Deserialize, Debug)]
struct FlatKeyValue<K, V> {
    key: K,
    #[serde(flatten)]
    value: V,
}

fn main() {
    let list = AsList {
        items: [("a".to_owned(), Ty { foo: 0, bar: 1 })].into(),
    };

    let j = serde_json::to_string_pretty(&list).unwrap();
    println!("{j}");

    let l2: AsList = serde_json::from_str(&j).unwrap();
    println!("{l2:?}");
}
```

</details>

**Comment by cyqsimon** [comment]
Got it. Don't quite understand everything you said here, but the TLDR seems to be that there are technical difficulties with a generic implementation.

Yeah, using `#[serde(into)]` and `#[serde(from)]` seems easy enough. Will do that.

Not sure how exactly you want to handle this issue, so I'll leave it as is. Please do with it what you see fit.

**Comment by cyqsimon** [comment]
I ran into something very similar again just now:

I have the following json:

```json5
[
    { "key": { "id": "id0" }, "val": { "data": "data0" }},
    { "key": { "id": "id1" }, "val": { "data": "data1" }},
    // ...
]
```

... that I wish to deserialize into a `HashMap<Key, Val>` where:

```rust
struct Key { id: String }
struct Val { data: String }
```

---

Overall I think this is very similar to what I was looking for in this issue originally, the only difference being:

1. I'm looking for deserialisation this time.
2. This is spiritually similar to [adjacently tagged enum representation](https://serde.rs/container-attrs.html#tag--content) instead of internally tagged.

I assume the advice is the same, i.e. just use a `#[serde(from)]`?
