### ISSUE TITLE
dont fail silently if #[serde_as] is after derive

### ISSUE THREAD

**Issue by mirsella** [jonasbb/serde_with#795]
if by mistake the user doesn't put the serde_as after the derive attribute, serde_as will not work, but will not say anything.
a compile error would be really useful for the DX of this crate

thanks !

**Comment by jonasbb** [comment]
Hi, this sounds like a great addition. Unfortunately, I am not aware how to generally check if the `#[serde_as]` attribute gets consumed. If you have a robust way to check I happily review a PR for it.

**Comment by mirsella** [comment]
sadly I don't have enough knowledge about procedural macros.

I thought the #[serde_as] was still getting run even if it's after the derive, just that it wasn't compatible, because it needed the derive Serialize and Serialize.

I'll do some research but it's probably not possible as you say

have a good day

**Comment by mirsella** [comment]
just for my personal knowledge, the attribute macro doesn't run (doesn't get consumed) if it's after the derive macro ?
or it get run but do nothing because it want the derive after ?
like why does it need to be first

**Comment by jonasbb** [comment]
> like why does it need to be first

The macros get executed in order. If the derive is first all the code gets generated. Then the `serde_as` runs and modifies the type by placing more attributes on the fields. But since the derives already ran, they don't react to the attributes.

**Comment by mirsella** [comment]
ohh ok, thanks a lot for the explanation. isn't it possible to detect if the dervie Serialize/Deserialize already run and generated code ? 
like check if there is already a `impl _serde::Serialize` on the struct, or even if there is no `#[derive()` under on the struct ?
problem with manual impl of serde Serialize/Deserialze ?
