### ISSUE TITLE
Generated schemas are not valid when using Rust style names in ref

### ISSUE THREAD

**Issue by waltronix** [jonasbb/serde_with#798]
Not all generated schemas are valid. Especially when using the Rust style names with `<`, `>`, or `, ` for schema name generation it breaks schema validation.

I suggest to add a validation check to `declare_snapshot_test` and then change the generated names #799

**Comment by waltronix** [comment]
The problem does not come from the `,` itself, but from the space after it.

**Comment by jonasbb** [comment]
Closed with #799
